# Generated by Django 5.1.4 on 2024-12-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='weight_1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='weight_2',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='question',
            name='weight_3',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='question',
            name='weight_4',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='question',
            name='weight_5',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_1',
            field=models.CharField(default='Strongly Disagree', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_2',
            field=models.CharField(default='Disagree', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_3',
            field=models.CharField(default='Neutral', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_4',
            field=models.CharField(default='Agree', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_5',
            field=models.CharField(default='Strongly Agree', max_length=100),
        ),
    ]
