# Generated by Django 5.1.4 on 2025-01-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0003_question_weight_1_question_weight_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBTIDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti_type', models.CharField(max_length=4, unique=True)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
