# Generated by Django 5.1.4 on 2025-01-08 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0006_remove_mbtidescription_is_vague_mbtisentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbtisentence',
            name='mbti_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbti.mbtidescription'),
        ),
    ]
