# Generated by Django 5.1.4 on 2025-01-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0008_mbtidescriptionmodified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbtisentencemodified',
            name='correct_mbti_type',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='mbtisentencemodified',
            name='is_incorrect',
            field=models.BooleanField(default=False),
        ),
    ]
