# Generated by Django 5.1.4 on 2025-01-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0009_mbtisentencemodified_correct_mbti_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbtidescriptionmodified',
            name='wrong_mbti_type',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
