# Generated by Django 5.1.4 on 2025-02-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0010_mbtidescriptionmodified_wrong_mbti_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBTIVagueSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti_type', models.CharField(max_length=4)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('mbti_type', 'text')},
            },
        ),
    ]
