# Generated by Django 5.1.4 on 2025-02-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0011_mbtivaguesentence'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBTIVagueBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti_type', models.CharField(max_length=4, unique=True)),
                ('vague_text_block', models.TextField(help_text='Store multiple vague sentences separated by line breaks')),
            ],
        ),
    ]
