# Generated by Django 5.1.4 on 2025-03-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0012_mbtivagueblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbtivagueblock',
            name='vague_text_block',
            field=models.TextField(help_text='Store multiple vague sentences with explanations, each line in the format: sentence::explanation'),
        ),
    ]
